---
formatter:
  type: basic
  include_document_start: true
  retain_line_breaks_single: true
  trim_trailing_whitespace: true
  eof_newline: true
  line_ending: lf
  max_line_length: 80
  pad_line_comments: 1
  scan_folded_as_literal: true
