#!/usr/bin/env sh

set -e

FILES=$(git diff --cached --name-only --diff-filter=ACM "*.ts")

if [ -n "$FILES" ]
then
  echo "Check code format..."
  echo -n "  => "
  deno fmt --check $FILES

  echo "Check code lint..."
  echo -n "  => "
  deno lint $FILES
fi
